// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_7mUKU3ql6wYyZOuueXvTmAEbKqcxwmY',
    appId: '1:795779410771:web:075ba831c6e0d260c10fa6',
    messagingSenderId: '795779410771',
    projectId: 'locket-clone-app',
    authDomain: 'locket-clone-app.firebaseapp.com',
    storageBucket: 'locket-clone-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Ebj-vcSGXKmwyg7SZ-lvMIJNKFf8CyM',
    appId: '1:795779410771:android:cb4d614818137e88c10fa6',
    messagingSenderId: '795779410771',
    projectId: 'locket-clone-app',
    storageBucket: 'locket-clone-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuYCPF4gfFOfm8bsYjnKglaumCNSXTN6E',
    appId: '1:795779410771:ios:c351cf9324cc4e25c10fa6',
    messagingSenderId: '795779410771',
    projectId: 'locket-clone-app',
    storageBucket: 'locket-clone-app.firebasestorage.app',
    androidClientId: '795779410771-b6vrkfaumvjbi9ddnadnqg5atc1iqr8j.apps.googleusercontent.com',
    iosClientId: '795779410771-hmdl1f1rgfog4fg3vapqni73481lf2ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.locketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuYCPF4gfFOfm8bsYjnKglaumCNSXTN6E',
    appId: '1:795779410771:ios:c351cf9324cc4e25c10fa6',
    messagingSenderId: '795779410771',
    projectId: 'locket-clone-app',
    storageBucket: 'locket-clone-app.firebasestorage.app',
    androidClientId: '795779410771-b6vrkfaumvjbi9ddnadnqg5atc1iqr8j.apps.googleusercontent.com',
    iosClientId: '795779410771-hmdl1f1rgfog4fg3vapqni73481lf2ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.locketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_7mUKU3ql6wYyZOuueXvTmAEbKqcxwmY',
    appId: '1:795779410771:web:e408e4a5a8d05d95c10fa6',
    messagingSenderId: '795779410771',
    projectId: 'locket-clone-app',
    authDomain: 'locket-clone-app.firebaseapp.com',
    storageBucket: 'locket-clone-app.firebasestorage.app',
  );

}